### PR TITLE
changes in match_dataphy function

### PR DESCRIPTION
**Pull request by paternogbc**
Hi Caterina,

I had problems using match_dataphy in my computer with the function samp_phylolm etc...
I have made some modifications to this functions. Could you please check if you agree.
The most important part is using the function `model.frame` 

> model.frame(formula = formula, data = data, na.action = na.pass )

Which crops the dataset only with the variables present in the formula! Very nice function. With this I think we make the code simpler. Also, solves some errors.
If you think the changes are ok, you can merge the pull request to the master. =)

Cheers,
Gustavo

### CODE REVIEW

**Comment by caterinap** [comment]
Hi,

Nice function indeed, but this might not work with intra_phylolm. In this function people will give a formula AND 1 or 2 column names containing information on trait variability. So I would prefer to do the matching on the whole data provided by the user... The rest of the changes are ok for me!

**Comment by paternogbc** [comment]
I understand...

I think this wont be a problem because the:
> data.out <- data.0[rownames(data),]
  return(list(data,phy))		+
  return(list(data = data.out,phy = phy))

return the full dataset (all variables) but with croped rows from species removed. 
The code:
> data.out <- data.0[rownames(data),]

do this at the very end of the function. It uses the rownames of the croped data, to crop the original data set "data.0", saved at the bigning of the function. Then it saves this at the data.out object, which is what the function will return. 
I am not sure if this will work for intra_xxx ... 
Could you try that?

cheers

**Comment by caterinap** [comment]
Sorry, did not notice:
data.out <- data.0[rownames(data),]
Very nice, it works for me!
I made a small change, if you are ok, we can merge the branches!

**Comment by paternogbc** [comment]
super!!! =)) lets merge the branch ahuhauhau!

**Pull request merged**
