### PR TITLE
miss.phylo.d

### PR DESCRIPTION
**Pull request by caterinap**

### CODE REVIEW

**Comment by paternogbc** [comment]
One question: does any other package calculates this measure?
We are including a complete new package dependency (caper) in sensiPhy just to calculate this specific metric. 

Maybe we change from depends to imports in the description file.

**Comment by caterinap** [comment]
Yeah I know that is is a lot of caper and not a lot of ours.. We can still stop before step4 (see [here](https://github.com/paternogbc/sensiPhy/issues/112)). But I did not find anything in the literature..

**Comment by caterinap** [comment]
Travis check fails because of this:

> ERROR: dependency ‘stringr’ is not available for package ‘reshape2’
> removing ‘/usr/local/lib/R/site-library/reshape2’
> ERROR: dependency ‘munsell’ is not available for package ‘scales’
> removing ‘/usr/local/lib/R/site-library/scales’
> ERROR: dependencies ‘reshape2’, ‘scales’ are not available for package ‘ggplot2’
> removing ‘/usr/local/lib/R/site-library/ggplot2’

These are packages that are needed by ggplot2. I don't see why it fails in this branch and not in the `clade_permutation` branch..

**Comment by caterinap** [comment]
Little progress here: it might be an Ubuntu related error (Travis works on Ubuntu). `devtools::check` doesn't give me any error on Windows10 and Window8.

**Comment by caterinap** [comment]
Youpi!! I finally found the way to solve the errors! Just load some packages in the travis.mml file :)

**Comment by paternogbc** [comment]
You rock!!!!!!

Em 5 de out de 2016 08:16, "Caterina Penone" <notifications@github.com>
escreveu:

**Comment by caterinap** [comment]
I still have to do very few minor changes and then can I merge?

**Comment by paternogbc** [comment]
Yes sure =)

**Pull request merged**
